name: Build & Deploy Spring app v1.0

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      DATASOURCE_URL: ${{ secrets.DB_URL }}
      DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      FRONTEND_URL: https://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build the application (skip tests)
        run: mvn clean package -DskipTests -B --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/movie-reviews:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/movie-reviews:${{ github.sha }}
          build-args: |
            DATASOURCE_URL=${{ secrets.DB_URL }}
            DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}
            DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
            FRONTEND_URL=https://localhost:3000

      - name: Verify Docker image
        run: |
          echo "Docker image built and pushed successfully:"
          echo "${{ secrets.DOCKER_HUB_USERNAME }}/movie-reviews:latest"
          echo "${{ secrets.DOCKER_HUB_USERNAME }}/movie-reviews:${{ github.sha }}"

