name: Build, Analyze & Deploy Spring app v2.0

on:
  push:
    branches:
      - master

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run tests with coverage
        run: mvn clean test -B --file pom.xml -Dmaven.test.failure.ignore=true

      - name: Run SonarQube analysis with Maven (Force JDK 17)
        run: |
          export JAVA_HOME=${{ env.JAVA_HOME_17_X64 }}
          export PATH="$JAVA_HOME/bin:$PATH"
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-deploy:
    runs-on: ubuntu-latest
    needs: sonar-analysis
    env:
      DATASOURCE.URL: ${{ secrets.DB_URL }}
      DATASOURCE.USERNAME: ${{ secrets.DB_USERNAME }}
      DATASOURCE.PASSWORD: ${{ secrets.DB_PASSWORD }}
      FRONTEND_URL: https://localhost:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application (skip tests)
        run: mvn clean package -DskipTests -B --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/movie-reviews:latest
            ${{ secrets.DOCKER_USERNAME }}/movie-reviews:${{ github.sha }}
